### ISSUE TITLE
有没有办法做极大的json字符串的流式的解析

### ISSUE THREAD

**Issue by hyj1991** [zoubin/stream-handbook#6]
如题，有处理几百M甚至上G的大 JSON 需求，看到这个系列，很详细的看完了，确实写的很不错
不知道你们有没有这样的思路~

**Comment by zoubin** [comment]
感觉这种情况下你可能不需要一次拿到整个结果，而是某条路径对应的值，可以考虑一下 https://github.com/dominictarr/JSONStream 或 https://github.com/chrisdickinson/json-parse-stream

**Comment by hyj1991** [comment]
@zoubin 我研究下看看
话说之所以遇到这么大的 json 场景，是因为想做在线的 memory 内存分析... 而实时输出的内存快照很大很大...

谢谢你哇
